name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  unit-test:
    container: cuaesd/aesd-autotest:24-unit-test
    runs-on: self-hosted

    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning workspace..."
          rm -rf *
          rm -rf .git

      - name: Manual checkout at commit
        run: |
          echo "Cloning repository"
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git checkout $GITHUB_SHA
          git reset --hard $GITHUB_SHA
          git submodule sync
          git submodule update --init --recursive
          cp -r . ..

      - name: Confirm checked out commit
        run: |
          echo "HEAD: $(git rev-parse HEAD)"
          git log -1

      - name: Install kernel build dependencies
        run: |
          apt-get update
          apt-get install -y \
            gcc-aarch64-linux-gnu \
            flex \
            bison \
            libssl-dev \
            libelf-dev \
            bc \
            psmisc
      - name: Run unit test
        run : ./unit-test.sh



      - name: Run fulltest
        run: ./full-test.sh
